### ISSUE TITLE
doesn't work in AMD environment

### ISSUE THREAD

**Issue by Nek** [satazor/js-spark-md5#13]
I have a module defined like this

```
define(['jquery', 'md5', 'Bacon'], function ($, md5, Bacon) {
    console.log($);
    console.log(md5);
    console.log(Bacon);
}
```

Assuming the paths are right this logs me some code for $ and Bacon but undefined for md5.
If I edit md5.js and change the line

```
define('spark-md5', factory);
```

to

```
define(factory);
```

the problem is gone.

**Comment by winfan** [comment]
jquery  and sparkMD5 is not defined?
