### ISSUE TITLE
v1.0.1 is not published to NPM

### ISSUE THREAD

**Issue by angelaigreja** [satazor/js-spark-md5#34]
Could you please publish 1.0.1 to npm?

2.0.0 break my use case because I would rather use the original hash calculation instead of the hex string.

**Comment by satazor** [comment]
Sorry I forgot to publish 1.0.1

It's done now. Thanks for the heads up.

**Comment by windsome** [comment]
leak document. what's npm name?

**Comment by satazor** [comment]
@windsome spark-md5
