### ISSUE TITLE
Cannot get partial hash and continue

### ISSUE THREAD

**Issue by DzonnyDZ** [satazor/js-spark-md5#39]
I wanted to compute hash the way that I would compute hash for one chunk, get it, and than continue computing hash for chunks 1+2, get it; then 1+2+3 etc. Basically I need the incremental hash computing and as I'm computing it I need the intermediate hashes. But this is not working. I'm getting wrong hashes.

**Comment by satazor** [comment]
Can create a failing test?

**Comment by satazor** [comment]
Closing due to no feedback.
