### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Alex-Vaduva** [satazor/js-spark-md5#45]
Hi,
I've seen that  js-spark-md5 is based on work by Joseph Myers. Is it possible to know the original license for the Joseph Myers' code?
Thank you,
Alex

**Comment by satazor** [comment]
Here's the algorithm: http://www.myersdaily.org/joseph/javascript/md5-text.html
There's no mention to any license though.

Perhaps you could try to get in touch with him?

**Comment by Alex-Vaduva** [comment]
It's true, there is no license mentioned. Maybe the code is under GPL, or maybe the author would ask for money. I found this email address: Joseph Myers <josephmyers@yahoo.com> You could write him, if you want to clarify the licensing terms.

**Comment by satazor** [comment]
I've sent him an email, lets wait.

**Comment by satazor** [comment]
I've got the following reply:

André,

> Yes, that is fine. I have placed my code into the public domain. I appreciate so much your letting me know that you are using it for this important project! Best wishes to you!

> Sincerely,
> Dr. Joseph Myers
