### ISSUE TITLE
Seems like it doesn't work in Edge for cyrillic symbols

### ISSUE THREAD

**Issue by Safe-Mode** [satazor/js-spark-md5#54]
I try to hash domain "нашеправо24.рф"

should be: c6d317eda9b11438faa67a0977f0d9a1
but instead: 14effa5c5ede3c687e762efbcc7e26a7

Just in Edge. Other browsers (Chrome, Forefox) do the job well.

**Comment by Safe-Mode** [comment]
Sorry, I just need punnycode, issue is not actual anymore

**Comment by satazor** [comment]
Alright, closing.
