### ISSUE TITLE
spark.end();  The results after two executions are different

### ISSUE THREAD

**Issue by mypridelife** [satazor/js-spark-md5#55]
worng code: `spark.end()` executed twice
```
console.log(spark.end())
callBack(spark.end())
```
true code:
```
 tmp_md5 = spark.end()
 callBack(tmp_md5)
```
I found that the results after two executions are different.
the executions code is `spark.end()`

I didn't look at the source code carefully, so I hope the author answers

**Comment by charliemday** [comment]
On calling `spark.end()` the internal spark state resets itself (see line: 506 - https://github.com/satazor/js-spark-md5/blob/master/spark-md5.js#L524)

The work around for this could be to save the current state and reset the state immediately before calling `spark.end()` again.

e.g.

`const sparkState = spark.getState();`
`console.log('Correct MD5', spark.end());`
`console.log('Reset MD5', spark.end());`
`spark.setState(sparkState);`
`console.log('Correct MD5, spark.end());`

**Comment by mypridelife** [comment]
I understand, thank you
