### ISSUE TITLE
md5 error ( d41d8cd98f00b204e9800998ecf8427e for all big files than 600M)

### ISSUE THREAD

**Issue by bnuzhouwei** [satazor/js-spark-md5#64]
On big files: the method returen an error result

SparkMD5.hashBinary(e.target.result)

It test if file bigger than 600M, the result will be error, always get d41d8cd98f00b204e9800998ecf8427e 
and if file smaller than 300M, it work well.

**Comment by satazor** [comment]
For big files, use the incremental approach. Please check the readme.
